apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-metrics-config
  namespace: alloy-metrics 
data:
  config.alloy: |-

    discovery.kubernetes "pod" {
      role = "pod"
    }

    prometheus.scrape "pods" {
      targets    = discovery.kubernetes.pod.targets
      forward_to = [prometheus.remote_write.mimir.receiver]
    }

    otelcol.receiver.otlp "default" {
      grpc {}
      http {}
      output {
        metrics = [otelcol.processor.batch.default.input]
      }
    }

    otelcol.processor.batch "default" {
      output {
        metrics = [otelcol.exporter.prometheus.default.input]
      }
    }

    otelcol.exporter.prometheus "default" {
      forward_to          = [prometheus.remote_write.mimir.receiver]
      include_target_info = true
    }

    prometheus.remote_write "mimir" {
      endpoint {
        url = "http://mimir-gateway.mimir.svc.cluster.local/api/v1/push"

        tls_config {
          insecure_skip_verify = true
        }

        write_relabel_config {
          action       = "replace"
          target_label = "otlp"
          replacement  = "true"
        }
      }
    }
