apiVersion: v1
data:
  config.alloy: |-

    otelcol.receiver.otlp "default" {
      grpc {}
      http {}

      output {
        traces  = [otelcol.processor.k8sattributes.default.input]
      }
    }

    otelcol.processor.k8sattributes "default" {
      extract {
        metadata = [
          "k8s.pod.uid",
          "k8s.pod.start_time",
          ]
      }
      output {
        traces  = [otelcol.processor.batch.default.input]
      }
    }

    otelcol.processor.batch "default" {
      output {
        traces  = [otelcol.exporter.otlp.tempo.input]
      }
    }

    otelcol.exporter.otlp "tempo" {
      client {
        endpoint = "tempo-distributor.tempo.svc.cluster.local:4317"
        tls {
          insecure = true
          insecure_skip_verify = true
        }
      }
    }

kind: ConfigMap
metadata:
  name: alloy-traces-config
  namespace: alloy-traces 